import {
  Button,
  Card,
  CardContent,
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableRow,
  Typography,
} from '@mui/material';
import React from 'react';

const ReportsTable = ({ reports }) => (
  <Card>
    <CardContent>
      <Typography variant="h6" gutterBottom>
        Generated Reports
      </Typography>
      <Table size="small">
        <TableHead>
          <TableRow>
            <TableCell>Report ID</TableCell>
            <TableCell>Generated By</TableCell>
            <TableCell>Created</TableCell>
            <TableCell>Summary</TableCell>
            <TableCell align="right">Actions</TableCell>
          </TableRow>
        </TableHead>
        <TableBody>
          {reports.map((report) => (
            <TableRow key={report.id}>
              <TableCell>{report.id}</TableCell>
              <TableCell>{report.generated_by}</TableCell>
              <TableCell>{new Date(report.created_at).toLocaleString()}</TableCell>
              <TableCell>{report.summary?.slice(0, 80) || '—'}</TableCell>
              <TableCell align="right">
                <Button size="small" variant="outlined">
                  View
                </Button>
              </TableCell>
            </TableRow>
          ))}
          {reports.length === 0 && (
            <TableRow>
              <TableCell colSpan={5} align="center">
                <Typography variant="body2" color="text.secondary">
                  No reports yet.
                </Typography>
              </TableCell>
            </TableRow>
          )}
        </TableBody>
      </Table>
    </CardContent>
  </Card>
);

export default ReportsTable;
